# Generated by Django 5.0 on 2023-12-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='desc2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
